### ISSUE TITLE
Add マガポケ / マガジンポケット to Native (Japanese only) - First Party

### ISSUE THREAD

**Issue by antermin** [otakulogy/manga-platform#5]
Magapoke / マガポケ (https://pocket.shonenmagazine.com/series) is a service by Kodansha.

Series available on Magapoke include:
* Magapoke-only series
* Weekly Shonen Magazine series
* Bessatsu Shonen Magazine series

**Comment by crse** [comment]
Thank you for the information :) ( •̀ ω •́ )✧
