### ISSUE TITLE
Add COMIC FUZ to Native (Japanese only) - First Party

### ISSUE THREAD

**Issue by antermin** [otakulogy/manga-platform#6]
COMIC FUZ (https://comic-fuz.com) is a service by Houbunsha.

Series / magazines available on COMIC FUZ include:

* COMIC FUZ-only series
* Via subscription, latest issues of:
  * 週刊漫画TIMES
  * まんがタイム
  * まんがタイムオリジナル
  * まんがホーム
  * まんがタイムきらら
  * まんがタイムきららMAX
  * まんがタイムきららキャラット
  * まんがタイムきららフォワード
  * 花音
  * ｋｙａｐｉ！
* Series that are published on the above magazines

**Comment by crse** [comment]
Thank you for the contribution!
